# Generated by Django 3.2.6 on 2021-08-27 00:05

from django.db import migrations, models
import registration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150)),
                ('first_name', models.CharField(max_length=150)),
                ('other_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('education_qualification', models.CharField(max_length=150)),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('shop_location', models.CharField(max_length=150)),
                ('internet_usage', models.CharField(max_length=50)),
                ('skill', models.CharField(max_length=500)),
                ('working_duration', models.CharField(max_length=50)),
                ('deadline_handling', models.TextField(max_length=500)),
                ('project', models.TextField(max_length=500)),
                ('home_service', models.CharField(max_length=50)),
                ('expectation', models.TextField(max_length=500)),
                ('relevant_information', models.TextField(max_length=500)),
                ('passport', models.ImageField(blank=True, upload_to=registration.models.image_location)),
                ('work_evidence', models.FileField(blank=True, upload_to=registration.models.file_location)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
